# Generated by Django 6.1.1 on 2026-10-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='categoria',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
